name: Docker Build and Push
on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ github.ref }}
          dockerfile: Dockerfile
      - name: Slack notification on success
        if: success()
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: success
          title: Docker Build and Push
          message: |
            :white_check_mark: Build and push succeeded!
            Image: `${{ github.repository }}:${{ github.ref }}`
      - name: Slack notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: failure
          title: Docker Build and Push
          message: |
            :x: Build and push failed!
            Image: `${{ github.repository }}:${{ github.ref }}`