name: Docker Build

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker build -t portlisten:0.1 -f Dockerfile .
          secrets: |
            DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD}}

      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName
          mention: '@channel'
          channel: YourSlackChannel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}