name: Docker Build

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/sorokatyi/docker_build:${{ github.run_number }}
      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName
          mention: '@channel'
          channel: YourSlackChannel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}